### ISSUE TITLE
The new Assistant settings window is located quite away from the icon

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardAssistant#37] opened 2017-05-10 12:17 UTC
![image](https://cloud.githubusercontent.com/assets/26434103/25898200/b95d8840-3593-11e7-8e16-b9fed56a917f.png)

![image](https://cloud.githubusercontent.com/assets/26434103/25898239/e4b6891a-3593-11e7-89f5-07b5e5ef2eea.png)

The settings popover is too large

Reported here: 1479416

**Comment by ameshkov** [comment] 2017-07-27 09:52
Won't fix, that's by design

**Closed by ameshkov** 2017-07-27 09:52 UTC
Labels: wontfix
