### ISSUE TITLE
AdGuard Browser-Assistent greyed out in Firefox

### ISSUE THREAD

**Issue by glomeg132** [AdguardTeam/AdguardAssistant#372] opened 2022-02-20 10:22 UTC
I just started to use AdGuard for Mac OS and installed the browser extension AdGuard Browser-Assistet in Firefox 97.0.1. The version of the extension is 1.3.2 and AdGuard for Mac OS is on 2.7.0.1094. I have no other extensions installed on Firefox. The first start with Firefox looked good and AdGuard starts to block adds and trackers. After couple of minutes, even without any action on the keyboard, the AdGuard Browser-Assistent turns grey. It stays grey when opening other websites in new tabs. Clicking on the icon makes it green again. I'm not sure if AdGuard keeps working in the time the icon is grey. Restart Firefox also makes it green again. But after couple of minutes it turns grey again. On Reddit there is a discoussion about the same problem: 

https://www.reddit.com/r/Adguard/comments/s31ikm/browser_extension_icon_greyed_out_even_when_active/

Restart AdGuard Mac OS dosn't help.

**Comment by ameshkov** [comment] 2022-02-20 10:25
Hi, the issue is resolved in the latest AdGuard nightly version, you can find it here: https://adguard.com/beta.html

Or just wait for a couple more weeks, it will soon be pushed to stable update channel.

**Closed by ameshkov** 2022-02-20 10:25 UTC

**Comment by glomeg132** [comment] 2022-02-20 10:39
Thank you✌️
