### ISSUE TITLE
New Assistant: Assistant icon disappears

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#11] opened 2017-04-24 17:26 UTC
Assistant icon disappears when you scroll the page while dragging it.

STR: 
1. Click and hold Assistant icon to drag it.
2. Scroll to the bottom of the page. 

[Video ](https://screencast.com/t/Fs9YkUm3wdD6)

Same issue occurs if you scroll the page with mouse wheel.

**Comment by ameshkov** [comment] 2017-06-20 14:37
Duplicate of #47

**Closed by ameshkov** 2017-06-20 14:37 UTC
