### ISSUE TITLE
Assistant breaks captcha on kissasian.ch

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardAssistant#238] opened 2018-06-09 00:45 UTC
When the Assistant version 4.2.4 is active on the site https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fkissasian.ch%2FSpecial%2FAreYouHuman2%3FreUrl%3D%252fDrama%252fWhat-s-Wrong-With-Secretary-Kim%252fEpisode-2%253fid%253d37643 and you solve the captcha, you get wrong answer. When disabling Assistant it works fine.

https://github.com/AdguardTeam/AdguardFilters/issues/16631

**Comment by BlazDT** [comment] 2018-06-09 04:31
Another case: https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.spaste.com%2Fs%2FN4FCi0

**Comment by ameshkov** [comment] 2018-06-09 07:58
Duplicate of https://github.com/AdguardTeam/AdguardAssistant/issues/236

**Closed by ameshkov** 2018-06-09 07:58 UTC
Labels: duplicate
