### ISSUE TITLE
'Block ad on this website' does not work on Touch+Mouse devices like Surface

### ISSUE THREAD

**Issue by freezewind** [AdguardTeam/AdguardAssistant#140] opened 2017-10-08 04:23 UTC
Adguard  6.2.424.2123
Windows 10
firefox 54(disable multiprocess)
firefox 55-56

https://github.com/AdguardTeam/AdguardAssistant/issues/31
It is the same result with this issues.
In this issues, the firefox 54 is works for me, but it does work again when I update it.
The problem is multiprocess. The 'Block ad on this website' doesn't works when multiprocess enable.
I tested both original build and private builds.
 'Block ad on this website' doesn't work in firefox 55 or 56, and I cannot find a way to disable multiprocess in firefox 55 or 56.
PS. 'Block ad on this website' works with touch screen when multiprocess enables. This bug appears with mouse only.

**Comment by 4-life** [comment] 2017-10-10 15:48
Can't reproduce. I think it's not about multiprocess. @ameshkov what do you think?

**Comment by freezewind** [comment] 2017-10-10 17:20
I just install Chrome, and it also doesn't work.
The reason may be not about multiprocess, but my firefox actual doesn't work when multiprocess enable only.
Also, I create a new profiles to test this, so I don't think it related to old profile.

**Comment by ameshkov** [comment] 2017-10-10 17:22
@freezewind 
Hm, does not work in Chrome? What if we have a compatibility issue here with some other software or extension?

**Comment by freezewind** [comment] 2017-10-10 22:52
Yes, I don't install any extension in Chrome which I just installed for test, and I don't install any antivirus & security software exclusing windows defender.

**Comment by freezewind** [comment] 2017-10-13 04:08
@ameshkov
If you can not reproduce, you can remotely access my computer. Would it help you to fix this problem?

**Comment by ameshkov** [comment] 2017-10-13 08:51
@freezewind hope so, please email me to `am at adguard.com`

**Comment by ameshkov** [comment] 2017-10-13 23:42
@freezewind thanks for helping us!

@4-life I finally understood what was the issue. The thing is that @freezewind has a Surface device with a mouse. It supports BOTH mouse and touch events, but Assistant decides that "touch" is more important and ignores "mouse" events completely. I reckon we should be able to reproduce it on our Lenovo Yoga.

**Comment by ameshkov** [comment] 2017-10-13 23:44
Also, I see a weird error in the browser console (unrelated to this issue, but should be fixed):
`Adguard Assistant Beta.user.js:5591 GET https://www.google.com/i/s-wot.png 404 (Not Found)`

**Comment by freezewind** [comment] 2017-10-13 23:49
@ameshkov I am happy for helping you to fix this issue.

**Closed** 2017-10-16 11:37 UTC
Labels: bug
