### ISSUE TITLE
[Feature request] Add support for extended css rules in the devtools

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardAssistant#64] opened 2017-06-22 19:05 UTC
To debug extended css rules, currently one have to repeat adding several rules to user filter and refresh the page.

It would be helpful, if devtools provide ability to highlight elements matching a user-inputted selectors in ExtCss syntax, and provide ability to preview the page that the rule in action.

**Comment by ameshkov** [comment] 2017-06-28 14:53
Duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/756

**Closed by ameshkov** 2017-06-28 14:53 UTC
Labels: enhancement
