### ISSUE TITLE
Reporting the website is not working frequently

### ISSUE THREAD

**Issue by Bushido1** [AdguardTeam/AdguardAssistant#194] opened 2018-03-01 15:33 UTC
I use the latest beta of Assistant. The option "Report the website" is not working all the time. It is working only occasionally. This has not happened before.
Restarting the browser is the only solution that I have came up with.
![image](https://user-images.githubusercontent.com/11409601/36853270-aec3c310-1d76-11e8-89bf-9ec725793a42.png)

**Comment by ameshkov** [comment] 2018-03-01 15:34
What exact version of AdGuard? Nightly or stable?

**Comment by Bushido1** [comment] 2018-03-01 15:43
6.2.437.2171

**Comment by ameshkov** [comment] 2018-03-03 23:32
Is there any simple way to reproduce it?
What exactly is happening when you click "report the website"?

**Comment by Bushido1** [comment] 2018-03-04 06:57
The assistant is automatically closed and nothing else happens. I had this behaviour right now also.
TeamViewer is perhaps the best solution to reproduce it?

**Comment by ameshkov** [comment] 2018-03-04 09:37
Yep, I can take a look, but later. Could you plz poke me in Telegram?

**Comment by Bushido1** [comment] 2018-03-04 11:50
@ameshkov Indeed. I shall

**Comment by ameshkov** [comment] 2018-03-05 10:46
Closed as a duplicate of https://github.com/AdguardTeam/AdguardForWindows/issues/2138

**Closed by ameshkov** 2018-03-05 10:46 UTC
Labels: P3: Medium, bug
